// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFHcRLKYLJQqDj4KfiudgLDaGv_tyR1OQ',
    appId: '1:482449255647:web:867407322067a9a6a54d6a',
    messagingSenderId: '482449255647',
    projectId: 'wishlist-e0c79',
    authDomain: 'wishlist-e0c79.firebaseapp.com',
    storageBucket: 'wishlist-e0c79.firebasestorage.app',
    measurementId: 'G-1VLMTXQZP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZVYlLDRgt1scTa5aHENRx9AmH3m0dlw',
    appId: '1:482449255647:android:fcc8e64a592b81d2a54d6a',
    messagingSenderId: '482449255647',
    projectId: 'wishlist-e0c79',
    storageBucket: 'wishlist-e0c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-cyTUW5yG8n26Ic8qGC7Y4PwdjVItCF8',
    appId: '1:482449255647:ios:77b22c3b0a3fee30a54d6a',
    messagingSenderId: '482449255647',
    projectId: 'wishlist-e0c79',
    storageBucket: 'wishlist-e0c79.firebasestorage.app',
    iosBundleId: 'com.example.firebasePostsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-cyTUW5yG8n26Ic8qGC7Y4PwdjVItCF8',
    appId: '1:482449255647:ios:77b22c3b0a3fee30a54d6a',
    messagingSenderId: '482449255647',
    projectId: 'wishlist-e0c79',
    storageBucket: 'wishlist-e0c79.firebasestorage.app',
    iosBundleId: 'com.example.firebasePostsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFHcRLKYLJQqDj4KfiudgLDaGv_tyR1OQ',
    appId: '1:482449255647:web:c8a9f7ecb0e1f14ea54d6a',
    messagingSenderId: '482449255647',
    projectId: 'wishlist-e0c79',
    authDomain: 'wishlist-e0c79.firebaseapp.com',
    storageBucket: 'wishlist-e0c79.firebasestorage.app',
    measurementId: 'G-KVX9BZS8LY',
  );
}
